Cutting Indev to Master 0.19.0 (#196)
* [FEATURE/BUGFIX] Extendables (#155)

* (Hot fix) DM permissions (#156)

* Fixed DM permissions

Cannot read property 'permLevel' of null 
    at Object.exports.run (/inhibitors/permissions.js:9:22)

* Update package.json

* Update CHANGELOG.md

* Updated functions log, loadSingleFile and better error tracking. (#159)

* Error stack when the load fails.

My bad in the lastest PR I updated the line 50, I realized this line is for startup, should print just the error stack now.

* Resolve object to string.

Let's nuke all `[object Object]` from the logs.

* Removed util.inspect from app.js

The string is now parsed in the function log.

* Update CHANGELOG.md

* Update package.json

* Update CHANGELOG.md

* ESLint

* Resolve object to string.

Let's nuke all `[object Object]` from the logs.

* Display error inside a codeblock.

If the error comes from loadSingleCommand (the file exists but it's not cached on `client.commands`), it'll be shown inside a codeblock for better readability.

* Tweaked a bit the string from the reject

* Added syntax highlight to the codeblock

* [BUGFIX] Extendables for all Text Channels (#160)

* Bugfixes for the new extendables

* Patch Bump && Changelog

* (Hot fix) Help command not working properly (#162)

* Resolved a critical bug

* Update CHANGELOG.md

* Update package.json

* Added a missing semicolon.

* Superfast loaders (#163)

* Superfast loaders

Loading times:
108 commands, (~10.200loc) 35s => 6s (5.8x faster)
78 commands, (~6.400loc) 24s => 5s (4.8x faster)

* Update CHANGELOG.md

* Update package.json

* Less try/catch.

* Updated load

* Updated load

Now it shouldn't load the piece if it's previously loaded.

* Update CHANGELOG.md

* Update loadSingleCommand.js

* Fixed the loading order

Now they should load clientBase, then coreBase.

* Free the cache after loading the file

* Update CHANGELOG.md

* Delete loadCommandInhibitors.js

* Delete loadCommands.js

* Delete loadFunctions.js

* Delete loadProviders.js

* Delete loadMessageMonitors.js

* Delete loadEvents.js

* Delete parseTags.js

* Update reload.js

Now every piece removes the cache after loading the piece.

* Woops.

* Fixed awaitMessage, now it should prompt

* Update CHANGELOG.md

* Wooops.


Also fixes #158

* Readable Extendable (#164)

* Readable Extendable

* Changelog

* Embedable && Attachable changed to be more accurate

* Monitor Changes && Usage Fix (#165)

* Monitor Changes && Usage Fix

* oops

* Reaction Extend, Usage Fix && ReactionCollector (#166)

* <Message>.reactable && Usage Fixes... maybe

* isNaN Fix finally

* Changelog

* Kyra's AwaitMessage Fix

* Changelog

* More Usage Fixes

* Change undefined to null to prevent errors

* forgot to push

* more prompt fixes

* Fixed reactable

* More Usage Fixes

* Multiple Literal Usage fix

* Readd Silent Inhibitors.. whoops

* ReactionCollector(ing)

* Added ability to stop after x amount of same emoji

* [Hotfix] client.funcs.log is not a function (#168)

* Hotfix

Fixed the issue `client.funcs.log` is not a function.

* Update CHANGELOG.md

* Update package.json

* Multiple Prefix Fixes, ignore the branch name (#170)

* Multiple Prefix Fixes

* changelog

* blah

blah

* Update parseCommand.js

* Fuck you Cockroaches (bug fixes) (#172)

* More Config Fixes (#173)

* Fuck you Cockroaches (bug fixes)

* Add to all configs, not just default

* fix min error inside max

* Update dependencies to enable Greenkeeper 🌴 (#174)

* chore(package): update dependencies

https://greenkeeper.io/

* docs(readme): add Greenkeeper badge 

https://greenkeeper.io/

* Update package.json

* Update README.md

* oops

* Added heartbeat to ping command. (#176)

* Added heartbeat to ping command.

* Added heartbeat to ping command.

* Patch increment

* usage fix (#177)

* #169 fast fixes (#178)

* Catch the promises

* Validate booleans

* Update awaitMessage.js

* Update ping.js

* Update package.json

* Update CHANGELOG.md

* Re-connect if Disconnection Code is 1000 (#181)

* Re-connect if Disconnection Code is 1000

CLOSE_NORMAL (1000) >Normal closure; the connection successfully completed whatever purpose for which it was created.
From: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

* Update package.json

* Update CHANGELOG.md

* Revert "Re-connect if Disconnection Code is 1000 (#181)" (#182)

This reverts commit ba2a89d223167e9de688e2e999efa1a1ce243e10.

* Return of ParseTags due to Provider. (#184)

* Create parseTags.js

* Update package.json

* Update CHANGELOG.md

* Update .eslintrc

* MergeConfig (#187)

* MergeConfig

* mergeConfig utils addition

* Revert "MergeConfig (#187)" (#188)

This reverts commit a147435d162eb709bff7a101deed8c7d2e608df8.

* Fix Downloading *again* (#189)

* Update download.js

* Update package.json

* Update CHANGELOG.md

* Revert "Fix Downloading *again* (#189)" (#190)

This reverts commit 0b7800072d134fd7c2b32a7d51605cb0b08cc51b.

* enable/disable (#192)

* Update enable.js

* Update disable.js

* fix lint on disable

* fix enable lint

* take 2 fix lint disable

* take 2 fix lint enable

* Fix unexpected behavior with runIn inhibitor (#193)

* Fix Enable/Disable Commands (#194)

* Fix Disable Command Usage

* Fix Enable Command Usage

* Fix compatibility with v0.18.x in disable command

* Fix compatibility with v0.18.x in enable command

* Update package.json

* Changelog Updates

* Package JSON Update.

* Update .eslintrc